<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <UseSystemDrawing>true</UseSystemDrawing>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>PomodoredTimer.Windows.Public</AssemblyName>
    <RootNamespace>PomodoredTimer.Windows.Public</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PomodoredTimer.Domain\PomodoredTimer.Domain.csproj" />
    <ProjectReference Include="..\PomodoredTimer.Application\PomodoredTimer.Application.csproj" />
  </ItemGroup>
</Project>
